# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_add_change_history_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUnitNumber',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('school', models.ForeignKey(to='schools.School', blank=False, null=False, related_name='unit_numbers')),
                ('begin_day', models.IntegerField(blank=True, db_column='alkamispaiva', null=True, verbose_name='begin day')),
                ('begin_month', models.IntegerField(blank=True, db_column='alkamiskuukausi', null=True, verbose_name='start month')),
                ('begin_year', models.IntegerField(blank=True, db_column='alkamisvuosi', null=True, verbose_name='start year')),
                ('end_day', models.IntegerField(blank=True, db_column='paattymispaiva', null=True, verbose_name='end day')),
                ('end_month', models.IntegerField(blank=True, db_column='paattymiskuukausi', null=True, verbose_name='end month')),
                ('end_year', models.IntegerField(blank=True, db_column='paattymisvuosi', null=True, verbose_name='end year')),
            ],
            options={
                'permissions': (('change_history', 'Can change historical records'),),
                'verbose_name_plural': 'unit numbers',
                'abstract': False,
                'managed': True,
                'verbose_name': 'unit number',
            },
        ),
    ]
