# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_add_schoolunitnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='employership',
            name='principal',
            field=models.ForeignKey(blank=True, db_column='rehtorin_id', null=True, on_delete=models.deletion.SET_NULL, related_name='employers', to='schools.Principal', verbose_name='principal'),
        ),
        migrations.AddField(
            model_name='employership',
            name='school',
            field=models.ForeignKey(blank=True, db_column='koulun_id', null=True, on_delete=models.deletion.SET_NULL, related_name='principals', to='schools.School'),
        ),
        migrations.AlterModelOptions(
            name='employership',
            options={'managed': True, 'permissions': (('change_history', 'Can change historical records'),), 'verbose_name': 'employership', 'verbose_name_plural': 'employerships'},
        ),
    ]
