# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_make_employership_managed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employership',
            name='begin_day',
            field=models.IntegerField(blank=True, db_column='alkamispaiva', null=True, verbose_name='begin day'),
        ),
        migrations.AlterField(
            model_name='employership',
            name='begin_month',
            field=models.IntegerField(blank=True, db_column='alkamiskuukausi', null=True, verbose_name='start month'),
        ),
        migrations.AlterField(
            model_name='employership',
            name='begin_year',
            field=models.IntegerField(blank=True, db_column='alkamisvuosi', null=True, verbose_name='start year'),
        ),
        migrations.AlterField(
            model_name='employership',
            name='end_day',
            field=models.IntegerField(blank=True, db_column='paattymispaiva', null=True, verbose_name='end day'),
        ),
        migrations.AlterField(
            model_name='employership',
            name='end_month',
            field=models.IntegerField(blank=True, db_column='paattymiskuukausi', null=True, verbose_name='end month'),
        ),
        migrations.AlterField(
            model_name='employership',
            name='end_year',
            field=models.IntegerField(blank=True, db_column='paattymisvuosi', null=True, verbose_name='end year'),
        ),
        migrations.AlterField(
            model_name='employership',
            name='id',
            field=models.IntegerField(db_column='ID', editable=False, primary_key=True, serialize=False),
        ),
    ]
